global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'localnetworkprotector'
    static_configs:
      # If running LNP natively on host
      - targets: ['host.docker.internal:9464']
        labels:
          env: 'production'
